Fifo lifo mru policy
python-labs-2024/1_caching_decorator pull request #3
Opened 2024-10-29 14:33 UTC by DmitriyGubkovskiy

Добавил три политики с тестами и немного изменил порядок добавления и замещения. Просматривайте.

2024-10-29 15:19 UTC, vlgUseless reviewed
По логике особо ошибок не нашёл, есть по моему мнению лишние строчки в тестах и одна опечатка в докстринге функции test_cache_eviction_LRU, а в остальном всё ок.
Ждём, пока посмотрит Артём.

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
Мне кажется, не в этом месте стоит проверять, закэшировались ли значения. 
У нас тест проверяет правильно ли вытеснилось значение и поместилось новое, поэтому логичнее после вытеснения проверять, какие из значений в кэше: мы знаем, что slow_function(1) пересчиталось, так как счётчик увеличился, а вот про результаты slow_function(2) и slow_function(3) после замещения не уверены, в кэше ли они. Соответственно, логичнее вместо текущей проверки в самом конце добавить 
```python
    # Повторный вызов для кэшированной 2
    slow_function(2)
    assert slow_function.call_count == 4

    # Повторный вызов для кэшированной 3
    slow_function(3)
    assert slow_function.call_count == 4
```

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
> +    assert slow_function.call_count == 2
Аналогично тесту для LRU, проверку лучше вынести в конец и проверить оба значения на нахождение в кэше. Либо вообще убрать эти две строчки, они как будто за собой ничего не несут.

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
> +    assert slow_function.call_count == 2
Аналогично, зачем проверять, что у нас 2 в кэше? Или почему тогда проверяем, что только одно из двух значений в кэше?
Лучше убрать строчки, последующих тестов для замещения достаточно.

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
> +    assert slow_function.call_count == 4
Тут ошибка, потом исправил.

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
> +    assert slow_function.call_count == 2
Аналогично с остальными тестами, проверка лишняя.

2024-10-29 15:19 UTC, vlgUseless commented on tests/test_cache_decorator.py
> +    """Проверяет, что кэш очищает старые значения при превышении глубины  при политике LRU."""
Пробел лишний.

2024-10-29 15:53 UTC, Arity-T reviewed
На будущее, лучше было бы разделить разные политики на разные пул реквесты. Чем меньше пул реквест, тем проще его ревьювить и тем меньше вероятность ошибки. Каждый пул реквест - максимум одна фича, а иногда даже и большую фичу приходится разделять.

2024-10-29 15:56 UTC, Arity-T commented on tests/test_cache_decorator.py
Файл с тестами тоже стоило бы разделить на отдельные файлы для каждой политики. Это вообще хорошая практика в программировании, да и не только, если что-то хорошо по смыслу разделяется - надо разделять, чем меньше кода в каждой части, тем проще, тем меньше путаницы с именами, тем легче человеку - программисту, разобраться в вашем коде.

2024-10-29 16:19 UTC, Arity-T requested changes
Это неправильное поведение. Пользователь библиотеки даже не узнает, что что-то  не так. И на это стоит добавить тест.
```python
>>> from caching_decorator import cache
>>> @cache(policy="haha")
... def test(x):
...     return x + x
...
>>>
>>> test(10)
20
```

Но есть более серьёзная проблема, связанная с общим подходом. Декоратор отнюдь не универсальный. А что если нельзя хэшировать аргументы функции?
```python
>>> from caching_decorator import cache
>>> @cache()
... def test(x):
...     return x
... 
>>> test(10) 
10
>>> test(["a", "b"]) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "1_caching_decorator\caching_decorator\caching_decorator.py", line 25, in wrapper
    if key in cache:
       ^^^^^^^^^^^^
TypeError: unhashable type: 'list'
```

2024-10-30 04:39 UTC, Arity-T commented
Хэшировать произвольные объекты в любом случае не получится, потому что мы не знаем, насколько сложными они могут быть. Может быть в теории и можно сделать декоратор, который будет работать вообще с любыми объектами, однако, если это вообще возможно, он может быть очень медленным, что нам не подходит, ведь речь идёт про кэш.

Другими словами, нам просто нужно решить, с какими типами данных будет работать декоратор. Можно запариться и попытаться, опять же ценой производительности, расширить множество допустимых типов (как [тут](https://stackoverflow.com/questions/29596574/memoization-recipe-that-allows-non-hashable-arguments), например), но мне кажется, что у нас такой задачи не стоит. Нас вполне устроит множество `hashable` типов. Кстати, `functools.cache` из стандартной библиотеки python, тоже работает только с `hashable` аргументами.

В нашем случае исправление проблемы, заключается в дополнительном описании этого момента в `README.md` и, может быть, вывода более понятной для конечного пользователя ошибки, в которой бы сообщалось, что  декоратор работает только с `hashable` аргументами, чтобы пользователь точно знал, что ошибка вызвана не в коде его функции, а в нашем  декораторе. Можно дать рекомендации о том, что если пользователь хочет работать со своими классами, то ему потребуется определить метод `__hash__`, впрочем это уже необязательно.

2024-10-30 07:26 UTC, DmitriyGubkovskiy commented
Предлагаю закрыть этот pr, так как он чисто для политики. Начнем новый для обработки некэшируемых значений.

2024-10-30 15:25 UTC, Arity-T commented
Ты всё-таки решил ими (нехэшируемыми значениями) заняться? В любом случае, это, конечно, надо будет делать в отдельном PR. Однако комментарий про отсутствие проверки `policy` актален и должен быть исправлен в этом pr.

2024-10-30 15:34 UTC, Arity-T commented
Ещё стоит добавить тесты на то, что сами возвращаемые кэшем значения правильные. К тестам вообще подход такой - чем больше, тем лучше. Даже, если кажется, что тест бесполезен или есть сомнения в том, что его дублирует другой тест - лучше написать больше тестов, они есть и пить не просят, а уверенности добавляют.

2024-10-30 15:44 UTC, Arity-T commented
И `isort` в `test_cache_decorator.py` не применён был. К тому же бесполезный импорт `isort` надо удалить.

2024-11-07 08:37 UTC, Arity-T requested changes

2024-11-07 08:37 UTC, Arity-T commented on caching_decorator/caching_decorator.py
> +            except:
**Никогда** не надо использовать `try-except` без параметров. Всегда нужно как можно точнее указывать, какое исключение ты отлавливаешь `try-except` без параметров это super bad practice.
В редких случаях (e. g. верхнеуровневый слой какого-нибудь вебсервера) можно использовать `except Exception` разве что (причём это более узкое множество ошибок, чем без параметров). 

И, ключевой вопрос, он не такой простой как кажется, сначала над тем, что выше писал надо подумать. Так вот: _надо ли вообще отлавливать тут это исключение?_ На досуге можно почитать [стайтеку на тему](https://habr.com/ru/articles/853056/).

2024-11-07 08:37 UTC, Arity-T commented on caching_decorator/caching_decorator.py
> +            if depth is not None and depth > 0:
Вопрос на засыпку: А что будет если в `depth` указать `None`?
И ещё более интересный вопрос: Нужны ли вообще эти проверки `depth is not None`?

2024-11-13 07:06 UTC, Arity-T approved these changes
Ну вроде всё ок

2024-11-13 07:24 UTC, merged